# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37e4492e10951e58578a94c01cf679c0c012397716402f110996a69c285670c85392b3bb00929f8deeace9ec4ac41900f2fdb9140443e0d8e16f38b65af79f57

test:
  secret_key_base: 689192e86a67f743d7d7bd1e22276d29fbe8f8ee0716dde305c40ff92053a6d0f0423cc2bccdaafc26542baf8c9f9fca46cdbb1d138c9b91b146cd9401ce809d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
